### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by mniak** [ProCode-Software/BiblePuzzle#5]
**Describe the bug**
After typing the verse and the last space, I expected the cursor to move to the box at the bottom, where I would type the verse reference. I have tried to press Tab, Space more times, Arrow Down, click on the box, but nothing happens.

**To Reproduce**
Open https://procode-software.github.io/BiblePuzzle/, and type a vers  and its last space.
The cursor will not move to the Verse Reference box.

**Expected behavior**
The cursor should move to the box at the bottom, where I would type the verse reference

**Screenshots**
![image](https://github.com/ProCode-Software/BiblePuzzle/assets/1469412/e41e58fe-361e-4383-b0f0-3ca0664e3858)

**Device info**
 - **Device:** Desktop PC
 - **OS:** Linux
 - **Browser:** Firefox
 - **Version:** 113.0.1
 - **User agent:** `Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0`

**Comment by ProCode-Software** [comment]
Hi @mniak, thank you for playing BiblePuzzle! The bug had been caused with the new Narrator feature. It has been found and patched and typing should work as normal. Thanks for letting us know!
